// Generated by CoffeeScript 1.7.1
(function() {
  var parser, xml2js, xmlBodyParser;

  xml2js = require('xml2js');

  parser = new xml2js.Parser();

  xmlBodyParser = function(req, res, next) {
    var buf;
    if (req._body) {
      return next();
    }
    if (req.body == null) {
      req.body = {};
    }
    if ('GET' === req.method || 'HEAD' === req.method) {
      return next();
    }
    if (!('application/xml' === req.headers['content-type'] || 'application/xml' === (req.headers['content-type'] || '').split(';')[0])) {
      return next();
    }
    req._body = true;
    buf = '';
    req.setEncoding('utf8');
    req.on('data', function(chunk) {
      return buf += chunk;
    });
    return req.on('end', function() {
      var err;
      try {
        return parser.parseString(buf, function(err, json) {
          if (err) {
            throw err;
          }
          req.body = json;
          return next();
        });
      } catch (_error) {
        err = _error;
        err.status = 400;
        return next(err);
      }
    });
  };

  exports.xmlBodyParser = xmlBodyParser;

}).call(this);
